# Generated by Django 2.1.4 on 2019-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=6),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_class',
            field=models.PositiveSmallIntegerField(blank=True, default='', null=True),
        ),
    ]
